### ISSUE TITLE
Failed to load provided ReNet101 model

### ISSUE THREAD

**Issue by SJHNJU** [stresearch/xfr#2]
First of all , bigCon on good work!

when excutes demo/test_whitebox.py, I can not load pretrained ResNet101 model
**[pthfile] ../models/resnet101v4_28NOV17_train.pth**
    wb = Whitebox(WhiteboxSTResnet(stresnet101('../models/resnet101v4_28NOV17_train.pth')))
  File "../python\xfr\models\resnet.py", line 288, in stresnet101
    return resnet101v6(pthfile, device)
  **File "../python\xfr\models\resnet.py", line 279, in resnet101v6
    pretrained_state_dict = torch.load(pthfile)**
  File "D:\Anaconda3\lib\site-packages\torch\serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "D:\Anaconda3\lib\site-packages\torch\serialization.py", line 563, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
**_pickle.UnpicklingError: invalid load key, 'v'.**

Is it because the provided model are damaged or in other format?? Looking forward to your reply

**Comment by SJHNJU** [comment]
Same ERROR repeats when dealing with:

**models/resnet50_128_pytorch/resnet50_128.pth
models/senet50_256_pytorch/senet50_256.pth**

torch.load function cannot load those PTH

**Comment by williford** [comment]
It seems like you are having an issue with the data not downloading via GIT LFS. Can you confirm that you have those .pth files?

Please make sure you have `git lfs` installed:
`https://git-lfs.github.com/`

and run `git lfs install`.

**Comment by SJHNJU** [comment]
**Thank you very much! Now the model can be correctly loaded**

However when excuting test_whitebox.py. 
function **ebp()** returns an error.

 **File "E:/NAS_workspace/code.zoo/explainable/xfr/demo/test_whitebox.py", line 264, in <module>
    ebp()**
  File "E:/NAS_workspace/code.zoo/explainable/xfr/demo/test_whitebox.py", line 85, in ebp
    img_saliency = wb.ebp(x_probe, P)
  **File "../python\xfr\models\whitebox.py", line 503, in ebp
    P = self._mwp_to_saliency(P) if not mwp else P**
  File "../python\xfr\models\whitebox.py", line 457, in _mwp_to_saliency
    img = skimage.filters.gaussian(img, blur_radius)
  File "D:\Anaconda3\lib\site-packages\skimage\filters\_gaussian.py", line 118, in gaussian
    image = convert_to_float(image, preserve_range)
  File "D:\Anaconda3\lib\site-packages\skimage\_shared\utils.py", line 243, in convert_to_float
    image = img_as_float(image)
  File "D:\Anaconda3\lib\site-packages\skimage\util\dtype.py", line 336, in img_as_float
    return convert(image, np.float64, force_copy)
  File "D:\Anaconda3\lib\site-packages\skimage\util\dtype.py", line 236, in convert
    raise ValueError("Images of type float must be between -1 and 1.")
**ValueError: Images of type float must be between -1 and 1.**

**Comment by jebyrne** [comment]
What version of skimage do you have installed?

**Comment by SJHNJU** [comment]
0.13.1

**Comment by jebyrne** [comment]
We have tested this with scikit-image == 0.17.2.  We have updated the README to reflect this.    Please try installing a more recent version of scikit-image and see if you still get this error.
