### ISSUE TITLE
A potential bug for demo test_whitebox.py

### ISSUE THREAD

**Issue by RuoyuChen10** [stresearch/xfr#6]
I try the latest demo with `vipy==0.8.6` and most bug have solved, but I find that when run `test_whitebox.py`:

```shell
Traceback (most recent call last):
  File "test_whitebox.py", line 272, in <module>
    weighted_subtree_triplet_ebp(topk=64, mask='nose')
  File "test_whitebox.py", line 185, in weighted_subtree_triplet_ebp
    P_subtree = P_subtree.tolist()
AttributeError: 'list' object has no attribute 'tolist'
```

I think it may mask the row 185

```python
# P_subtree = P_subtree.tolist()
```

After that it raise:

```shell
Traceback (most recent call last):
  File "test_whitebox.py", line 272, in <module>
    weighted_subtree_triplet_ebp(topk=64, mask='nose')
  File "test_whitebox.py", line 195, in weighted_subtree_triplet_ebp
    vipy.util.imwrite(img_montage, f_montage)
  File "/home/cry/anaconda3/lib/python3.8/site-packages/vipy/util.py", line 300, in imwrite
    raise ValueError('image must by numpy object')
ValueError: image must by numpy object
```

I think it may change row 166 and 195

```python
vipy.util.imwrite(np.array(img_montage), f_montage)
```

**Comment by RuoyuChen10** [comment]
In row 165, I think it may change:

```python
img_montage = vipy.visualize.montage(imlist, imgheight=112, imgwidth=112, skip=False, border=1)
```

because in `vipy==0.8.6`, has remove the keyword `grayscale`

**Comment by RuoyuChen10** [comment]
After change, the code run over, most images is same as in path `xfr/demo/whitebox`

except 3 images `test_whitebox_weighted_subtree_ebp_*.jpg`:

only the last image can seen the heatmap mask, others can weakly seen, as follow:

![](https://gitee.com/Ruoyu_Chen/images/raw/master/img/test_whitebox_weighted_subtree_ebp_topk_64_mask_eyes.jpg)

look forward to your reply, thx.

**Comment by jebyrne** [comment]
This has been fixed, thanks for reporting.  Note that the version for vipy in the readme is vipy-0.8.16 and not vipy-0.8.6.
