### ISSUE TITLE
Model not found when running blackbox demo

### ISSUE THREAD

**Issue by biegt** [stresearch/xfr#8]
Hi,

I encountered an error when trying to run the blackbox demos (e.g., blackbox_demo_subject_0), indicating that the model to be used is not found:

`No such file or directory: '/home/tillb/Documents/Projects/xfr/models/resnet101_l2_d512_twocrop.pth`

The specified model is not in the current repository, so I was wondering what I can do get the model / run the demos.

Thanks!

**Comment by jebyrne** [comment]
Hi, all of the models in this repo are distributed using git-lfs.  Please see the installation instruction in the readme that discusses this issue.  

https://github.com/stresearch/xfr#installation

**Comment by visionjo** [comment]
Greetings @jebyrne:

The same issue persists. Git-lfs was installed, and some data and a few models were downloaded (e.g., `resnet101v4_28NOV17_train.pth`). The aligned data was unpacked, and the white-box demo could be run. 

Upon looking further, the above `resnet*_twocrop.pth` does not appear to be checked in.



```
$ git-lfs ls-files
.
.
.
e4c438e7ce * models/resnet101v4_28NOV17_train.pth
c8b59711ad * models/resnet50_128_pytorch/resnet50_128.pth
3a3c7e03fc * models/senet50_256_pytorch/senet50_256.pth
6c670033fa * python/strface/models/detection/bottom_layers.pth
.
.
.
```

If not too much of a hassle, please let us know if there is a direct link.

Thanks!
